apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: eks
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/Smana/flux-karpenter
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: eks-dev-hiving-hen
  namespace: flux-system
spec:
  interval: 8m
  approvePlan: auto
  path: ./terraform/dev
  destroyResourcesOnDeletion: true
  sourceRef:
    kind: GitRepository
    name: eks
    namespace: flux-system
  varsFrom:
    - kind: ConfigMap
      name: tfvars-dev-hiving-hen
    - kind: Secret
      name: github-credentials
  runnerPodTemplate:
    spec:
      image: smana/tf-runner:v0.15.0-rc.1
